export const GET_ORDERS_OF_CURRENT_USER = 'GET_ORDERS_OF_CURRENT_USER'
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const CREATE_ORDER = 'CREATE_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'

