export const GET_ALL_GOODS = 'GET_ALL_GOODS';

export const GOOD_ADD_START = 'GOOD_ADD_START';
export const GOOD_ADD_SUCCESS = 'GOOD_ADD_SUCCESS';
export const GOOD_ADD_ERR = 'GOOD_ADD_ERR';

export const GET_GOODS_OF_CURRENT_SELLER_ERR =
  'GET_GOODS_OF_CURRENT_SELLER_ERR';
export const GET_GOODS_OF_CURRENT_SELLER_START =
  'GET_GOODS_OF_CURRENT_SELLER_START';
export const GET_GOODS_OF_CURRENT_SELLER_SUCCESS =
  'GET_GOODS_OF_CURRENT_SELLER_SUCCESS';

export const GOOD_DELETE_SUCCESS = 'GOOD_DELETE_SUCCESS';
