export const GOOD_GET_START = "GOOD_GET_START";
export const GOOD_GET_SUCCESS = "GOOD_GET_SUCCESS";
export const GOOD_GET_ERR = "GOOD_GET_ERR";


export const GOOD_ADD_START = "GOOD_ADD_START";
export const GOOD_ADD_SUCCESS = "GOOD_ADD_SUCCESS";
export const GOOD_ADD_ERR = "GOOD_ADD_ERR";

export const GOOD_DELETE_START = "GOOD_DELETE_START";
export const GOOD_DELETE_SUCCESS = "GOOD_DELETE_SUCCESS";
export const GOOD_DELETE_ERR = "GOOD_DELETE_ERR";

export const GOOD_EDIT_START = "GOOD_EDIT_START";
export const GOOD_EDIT_SUCCESS = "GOOD_EDIT_SUCCESS";
export const GOOD_EDIT_ERR = "GOOD_EDIT_ERR";

